language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t react_test -f Dockerfile.dev .

script:
  - docker run -e CI=true react_test npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-docker"
  env: "Reactdocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-796488992137"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY

  