version: '3'
services:
    react-app:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - $PWD:/app
    react-app-test:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - $PWD:/app
        command: ["npm", "run", "test"]
    
    
    
   